### ISSUE TITLE
Shouldn't the web hook be private?

### ISSUE THREAD

**Issue by paulsapps** [k3rn31p4nic/travis-ci-discord-webhook#2]
Otherwise anyone can spam data to it?

**Comment by gpkc** [comment]
How is anyone gonna get it? If you turn off "display value in build log" when creating the env var, it will not appear for anyone.

**Comment by k3rn31p4nic** [comment]
As @gpkc said, it won't show if you disable viewing your Travis env. vars in your build log.

And btw, previously, I used the verbose flag (`-v`) for `cURL`, so that it will be easier for users to troubleshoot if a webhook fails to send for some reason, which also showed the webhook's link in plain text when making the request. That was a security issue, so I fixed that in https://github.com/k3rn31p4nic/travis-ci-discord-webhook/commit/42c4ee2c6d069498394663bf42e7db72142f70d4.
